import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Select, { SingleValue } from "react-select";
import SelectComponent, { OptionType } from "../src/components/select";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const options = [{ label: "option1", value: "option1" }];
  const handleChange = (val: SingleValue<OptionType>) => {
    console.log(val);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <SelectComponent<false>
          options={options}
          isMulti={false}
          onChange={(val) => {
            handleChange(val);
          }}
        />
        <Select
          options={options}
          isMulti={false}
          onChange={(val) => {
            handleChange(val);
          }}
        />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
